# Será utilizado variaveis de ambiente para facilitar as alterações futuras. 
version: "3.7"
networks:
  rotten_net:
    name: rotten_net
    driver: bridge
volumes:
  mongo_db_vol: {}

services:
  mongo_db:
    image: mongo:${MONGO_TAG}
    container_name: mongo_db
    networks:
      - rotten_net
    volumes:
      - mongo_db_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    
  rotten-potatoes:
    # # Usrá uma imagem já preparado do repositorio no DockerHub. 
    # image: afonsorf/rotten-potatoes:v1  
    
    # Será criado uma imagem a usando do Dockerfile do diretorio "./src/". Deixe a "build" comentada caso use uma imgamem pronta de Repositorios.
    build: 
      context: ./src/
      dockerfile: Dockerfile
    container_name: rotten-potatoes
    depends_on: 
      - mongo_db
    networks:
      - rotten_net
    ports:
      - "5000:5000"
    environment:
      MONGODB_HOST: mongo_db
      MONGODB_USERNAME: ${MONGO_USERNAME}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
